# Generated by Django 5.0.6 on 2024-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.URLField()),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
    ]
